### ISSUE TITLE
Epic Issue: Pop_OS Installer Wizard - Rust

### ISSUE THREAD

**Issue by rbevin777** [rbevin777/Pop_OS-_GUI_Helper_Wizard#9]
First Iteration Steps
1. [x] First thing we need to do is get a hello world project up and running
2. [ ] Next thing we need to do is modify it to have one option of a program to install
3. [ ] Then when we get one we can add 2 more
4. [ ] When 2 more have been added let's add a new tab and categorise.
5. [ ] When we have these apps added and categorised, we need to add tick boxes for already installed applications.
